{{- if .Values.environments }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-service.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.environments }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
