{{- if .Values.signedCookies }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-service.fullname" . }}-cloudfront
  namespace: {{ .Release.Namespace }}:
  annotations:
    {{- with .Values.secretAnnotations }}
      {{- toYaml . | nindent 8 }}
    {{- end }} 
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.signedCookies }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
