{{- if .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.secretAnnotations }}
      {{- toYaml . | nindent 8 }}
    {{- end }}
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
