apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name | quote }}
spec:
  ports:
    - name: http-fitwel
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      protocol: TCP
  selector:
    app: {{ .Values.app.name | quote }}
