{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "api.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.app.name }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- end }}
  tls:
    - hosts: 
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.app.name }}-cert
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
