{{- if .Values.signedCookies }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudfront
  namespace:  {{ .Release.Namespace | default "default"}}
type: Opaque
stringData:
  {{- range  $key, $value := .Values.signedCookies }}
  {{$key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}