apiVersion: v2
name: workflows-operator
description: A Helm chart for Fitwel workflows operator applications
type: application
icon: https://images.squarespace-cdn.com/content/v1/6294f761bc48c512bfad618b/0eb45243-5c6c-4a63-b1f0-38efc7493465/Fitwel+Logo+Website+Black.png?format=1500w
version: 0.1.0
kubeVersion: ">=1.29.0-0"
annotations:
  charts.openshift.io/name: workflows-operator
  charts.openshift.io/supportedVersions: ">=1.29.0"