{{- if .Values.environments }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-configmap
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
{{- toYaml .Values.environments | nindent 2 }}
{{- end }}
