{{- $releaseName := .Release.Name }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name | quote }}
  labels:
    app: {{ .Values.app.name | quote }}
spec:
  replicas: {{ .Values.deployment.replicaCount | default 1 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 0 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Values.app.name | quote }}
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.app.name | quote }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.app.name }}
      securityContext:
        {{ toYaml .Values.podSecurityContext | nindent 8 }}
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 5
      containers:
      - name: {{ .Release.Name | quote }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- if or .Values.environments .Values.secrets .Values.signedCookies }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NODE_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "$(NODE_HOST):4317"
        {{- range $key, $value := .Values.environments }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $releaseName }}-configmap
              key: {{ $key }}
        {{- end }}
        {{- range $key, $value := .Values.secrets }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $releaseName }}-secret
              key: {{ $key }}
        {{- end }}
        {{- range $key, $value := .Values.signedCookies }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $releaseName }}-cloudfront
              key: {{ $key }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.targetPort | default 8080 }}
        startupProbe:
          {{- with .Values.deployment.startupProbe }}
          {{- if .execProbeCommand }}
          exec:
            command:
            {{- range $index, $value := .execProbeCommand }}
            - {{ $value }}
            {{- end }}
          {{- else if .tcpSocket }}
          tcpSocket:
            port: {{ .tcpSocket }}
          {{- else }}
          httpGet:
            {{- if .httpHeaders }}
            httpHeaders:
            - name: {{ .httpHeaders.name | quote }}
              value: {{ .httpHeaders.value | quote }}
            {{- end }}
            path: {{ .path }}
            port: {{ .port | default 8080 }}
          {{- end }}
          failureThreshold: {{ .failureThreshold | default 10 }}
          periodSeconds: {{ .periodSeconds | default 5 }}
          {{- end }}
        livenessProbe:
          {{- with .Values.deployment.livenessProbe }}
          {{- if .execProbeCommand }}
          exec:
            command:
            {{- range $index, $value := .execProbeCommand }}
            - {{ $value }}
            {{- end }}
          {{- else if .tcpSocket }}
          tcpSocket:
            port: {{ .tcpSocket }}
          {{- else }}
          httpGet:
            path: {{ .path }}
            port: {{ .port | default 8080 }}
          {{- end }}
          initialDelaySeconds: {{ .initialDelaySeconds | default 5 }}
          periodSeconds: {{ .periodSeconds | default 1 }}
          timeoutSeconds: {{ .timeoutSeconds | default 1 }}
          successThreshold: {{ .successThreshold | default 1 }}
          failureThreshold: {{ .failureThreshold | default 1 }}
          {{- end }}
        readinessProbe:
          {{- with .Values.deployment.readinessProbe }}
          {{- if .execProbeCommand }}
          exec:
            command:
            {{- range $index, $value := .execProbeCommand }}
            - {{ $value }}
            {{- end }}
          {{- else if .tcpSocket }}
          tcpSocket:
            port: {{ .tcpSocket }}
          {{- else }}
          httpGet:
            path: {{ .path }}
            port: {{ .port | default 8080 }}
          {{- end }}
          initialDelaySeconds: {{ .initialDelaySeconds | default 5 }}
          periodSeconds: {{ .periodSeconds | default 1 }}
          timeoutSeconds: {{ .timeoutSeconds | default 1 }}
          successThreshold: {{ .successThreshold | default 1 }}
          failureThreshold: {{ .failureThreshold | default 1 }}
          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
