{{- $releaseName := .Release.Name }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name | quote }}
  labels:
    app: {{ .Values.app.name | quote }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  strategy:
    type: {{ .Values.strategy.type | default "RollingUpdate" }}
    {{- if .Values.strategy.rollingUpdate }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge | default "25%" }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable | default "25%" }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.app.name | quote }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app: {{ .Values.app.name | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name | default "default" }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      shareProcessNamespace: true
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}
      containers:
        - name: {{ .Release.Name | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: NODE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: $(NODE_HOST):4317
            {{- range $key, $value := .Values.environments }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $releaseName }}-configmap
                  key: {{ $key }}
            {{- end }}
            {{- range $key, $value := .Values.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $releaseName }}-secret
                  key: {{ $key }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.targetPort | default 8080 }}
          startupProbe:
            {{- if .Values.deployment.startupProbe.execProbeCommand }}
            exec:
              command:
                {{- range $index, $value := .Values.deployment.startupProbe.execProbeCommand }}
                - {{ $value }}
                {{- end }}
            {{ else if .Values.deployment.startupProbe.tcpSocket }}
            tcpSocket:
              port: {{ .Values.deployment.startupProbe.tcpSocket }}
            {{ else }}
            httpGet:
              {{- if .Values.deployment.startupProbe.httpHeaders }}
              httpHeaders:
                - name: {{ .Values.deployment.startupProbe.httpHeaders.name | quote }}
                  value: {{ .Values.deployment.startupProbe.httpHeaders.value | quote }}
              {{- end }}
              path: {{ .Values.deployment.startupProbe.path }}
              port: {{ .Values.deployment.startupProbe.port | default 8080 }}
            {{- end }}
            failureThreshold: {{ .Values.deployment.startupProbe.failureThreshold | default 10 }}
            periodSeconds: {{ .Values.deployment.startupProbe.periodSeconds | default 5 }}
          livenessProbe:
            {{- if .Values.deployment.livenessProbe.execProbeCommand }}
            exec:
              command:
                {{- range $index, $value := .Values.deployment.livenessProbe.execProbeCommand }}
                - {{ $value }}
                {{- end }}
            {{ else if .Values.deployment.livenessProbe.tcpSocket }}
            tcpSocket:
              port: {{ .Values.deployment.livenessProbe.tcpSocket }}
            {{ else }}
            httpGet:
              path: {{ .Values.deployment.livenessProbe.path }}
              port: {{ .Values.deployment.livenessProbe.port | default 8080 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds | default 15 }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds | default 20 }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds | default 1 }}
            successThreshold: {{ .Values.deployment.livenessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold | default 3 }}
          readinessProbe:
            {{- if .Values.deployment.readinessProbe.execProbeCommand }}
            exec:
              command:
                {{- range $index, $value := .Values.deployment.readinessProbe.execProbeCommand }}
                - {{ $value }}
                {{- end }}
            {{ else if .Values.deployment.readinessProbe.tcpSocket }}
            tcpSocket:
              port: {{ .Values.deployment.readinessProbe.tcpSocket }}
            {{ else }}
            httpGet:
              path: {{ .Values.deployment.readinessProbe.path }}
              port: {{ .Values.deployment.readinessProbe.port | default 8080 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds | default 5 }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds | default 1 }}
            successThreshold: {{ .Values.deployment.readinessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold | default 3 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- if .Values.affinity }}
        {{- toYaml .Values.affinity | nindent 8 }}
        {{- else }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ .Values.app.name | quote }}
              topologyKey: "kubernetes.io/hostname"  # Ensures pods are scheduled on different nodes
        {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
