{{- if .Values.signedCookies }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-cloudfront
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- toYaml .Values.signedCookies | nindent 2 }}
{{- end }}
