{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- toYaml .Values.secrets | nindent 2 }}
{{- end }}
