{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-template.fullname" . }}-secret
  labels:
    {{- include "app-template.labels" . | nindent 4 }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
