{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace:  {{ .Release.Namespace | default "default"}}
  annotations:
    {{- with .Values.secretAnnotations }}
      {{- toYaml . | nindent 8 }}
    {{- end }}
  labels:
    {{- include "app-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
