{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name | quote }}
  namespace: {{ .Release.Namespace | default "default"}}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ tpl (toYaml .Values.serviceAccount.annotations) . | indent 4 }}
{{- end }}
  labels:
    "app.kubernetes.io/instance": "{{ .Values.app.name }}"
{{- if .Values.serviceAccount.imagePullSecretName }}
imagePullSecrets:
  - name: {{ .Values.serviceAccount.imagePullSecretName }}
{{- end -}}
{{ end }}