name: Prod Push Docker Image

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Check out code portal-backend
        uses: actions/checkout@v3
        with:
          path: portal-backend
          token: ${{ secrets.GH_PAT }}

      - uses: actions/checkout@v3
      - name: Setup snyk
        run: |
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x snyk
          sudo mv ./snyk /usr/local/bin

      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Build variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          
      - name: Compile code
        run: make build

      - name: Test
        run: |
          CGO_ENABLED=0 go test ./...

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build image
        env:
          DOCKER_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          VERSION: ${{ steps.vars.outputs.sha_short }}
        run: make docker-build

      - name: Tag image and push to ECR
        id: send_to_ecr
        env:
          DOCKER_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          VERSION: ${{ steps.vars.outputs.sha_short }}
        run: make docker-release

      - name: Check out backend-deploy
        uses: actions/checkout@master
        with:
          repository: c4ad/backend-deploy
          token: ${{ secrets.GH_PAT }}
          path: backend-deploy
        id: tag_version
      - uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Render Prod backend deploy YAML
        uses: nowactions/envsubst@v1
        with:
          input: backend-deploy/apps/envs/prod/api-server.yaml.tmpl
          output: backend-deploy/apps/envs/prod/api-server.yaml
        env:
          IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}

      - name: Push changes
        working-directory: ./backend-deploy
        run: |
          echo "updated build id for production $(echo ${IMAGE_TAG})"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add apps/envs/prod/api-server.yaml
          git commit -m "updated build id for prod $(echo ${IMAGE_TAG})"
          git push

      - name: Send Slack Message
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "msg": "Production Backend Deployed",
              "deployer": "${{ github.actor }}",
              "pr": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "version": "${{ github.ref_name }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  tagged-release:
    needs: [build]
    if: |
          !contains(needs.build.send_to_ecr.result, 'success')
    name: "Generate Release"
    runs-on: ubuntu-latest

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
