{{- $releaseName := .Release.Name }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.app.name }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            {{- range $key, $value := .Values.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $releaseName }}-secret
                  key: {{ $key }}
            {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}
