{{- if .Values.secrets }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace:  {{ .Release.Namespace | default "default"}}
type: Opaque
stringData:
{{- range  $key, $value := .Values.secrets }}
  {{$key }}: {{ $value | quote }}
{{- end }}
{{- end }}
