{{- range $name, $app := .Values.applications }}
---
apiVersion: workflows.fitwel.org/v1
kind: WorkflowsOperator
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  {{- if $app.annotations }}
  annotations:
    {{- toYaml $app.annotations | nindent 4 }}
  {{- end }}
  basepath: {{ $app.basepath | quote }}
  replicas: {{ $app.replicas | default 1 }}
  domain: {{ $.Values.environment.domain | quote }}
  hpaMinReplicas: {{ $app.hpaMinReplicas | default 1 }}
  hpaMaxReplicas: {{ $app.hpaMaxReplicas | default 4 }}
  targetCPUUtilizationPercentage: {{ $app.targetCPUUtilizationPercentage | default 100 }}
  {{- if $app.serviceAccount }}
  serviceAccountName: {{ $app.serviceAccount }}
  {{- end }}
  {{- if $app.secrets }}
  secrets:
    {{- range $app.secrets }}
    - name: {{ .name | quote }}
      {{- if .secretName }}
      secretName: {{ .secretName | quote }}
      {{- end }}
      {{- if .mountPath }}
      mountPath: {{ .mountPath | quote }}
      {{- end }}
      {{- if .subPath }}
      subPath: {{ .subPath | quote }}
      {{- end }}
      {{- if .readOnly }}
      readOnly: {{ .readOnly }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if $app.ingress }}
  ingress:
    {{- range $app.ingress }}
    - enabled: {{ .enabled }}
      {{- if .ingressClass }}
      ingressClass: {{ .ingressClass }}
      {{- end }}
      {{- if .annotations }}
      annotations:
        {{- toYaml .annotations | nindent 8 }}
      {{- end }}
      {{- if .tls }}
      tls:
        {{- toYaml .tls | nindent 8 }}
      {{- end }}
      {{- if .rules }}
      rules:
        {{- toYaml .rules | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- end }}
  containers:
    {{- range $app.containers }}
    - name: {{ .name }}
      image: {{ tpl .image $ | quote }}
      {{- if .env }}
      env:
        {{- range .env }}
        - name: {{ .name }}
          {{- if .value }}
          value: {{ tpl .value $ | quote }}
          {{- else if .valueFrom }}
          valueFrom:
            {{- toYaml .valueFrom | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .resources }}
      resources:
        {{- toYaml .resources | nindent 8 }}
      {{- end }}
      {{- if .livenessProbe }}
      livenessProbe:
        {{- toYaml .livenessProbe | nindent 8 }}
      {{- end }}
      {{- if .readinessProbe }}
      readinessProbe:
        {{- toYaml .readinessProbe | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- if $app.service }}
  service:
    {{- range $app.service }}
    - enabled: {{ .enabled }}
      name: {{ .name | quote }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  {{- end }}
{{- end }}