{{- if .Values.volumes }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.app.name }}-storage
provisioner: {{ .Values.volumes.provisioner }}
volumeBindingMode: {{ .Values.volumes.bindingMode}}
allowVolumeExpansion: {{ .Values.volumes.allowVolumeExpansion }}
parameters:
  type: {{ .Values.volumes.type }}
{{- end }}