# Default values for api-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  name: api-service

image:
  repository: {} # aws ecr registry
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

deployment:
  replicaCount: 1
  startupProbe:
    tcpSocket: 8080
  livenessProbe:
    tcpSocket: 8080
    initialDelaySeconds: 40
  readinessProbe:
    tcpSocket: 8080
    initialDelaySeconds: 40

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

serviceAccount:
  create: true
  name: api-service
  annotations:
    eks.amazonaws.com/role-arn: {}

podAnnotations: {}

podSecurityContext: {}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  maxReplicas: 2
  cpu:
    targetAverageUtilization: 70
  memory:
    targetAverageUtilization: 70

behavior: {}

nodeSelector: {}

tolerations: []

affinity: {}

environments:
  # Example:
  # MONGODB_DATABASE_NAME: platform-live

secrets:
  # Example:
  # SECRET_KEY: my-secret-key

signedCookies:
  # Example:
  # PRIVATE_KEY: my-private-key
