# Default values for api-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  name: api-service

deployment:
  startupProbe:
      tcpSocket: 8080
  livenessProbe:
      tcpSocket: 8080
      initialDelaySeconds: 40
  readinessProbe:
      initialDelaySeconds: 40
      tcpSocket: 8080
  replicaCount: 1

image:
  repository: {} # aws ecr registry
  pullPolicy: IfNotPresent
  tag: "4441527"

nameOverride: ""
fullnameOverride: ""

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

environments: {}

serviceAccount:
  create: true
  name: api-service
  annotations:
    eks.amazonaws.com/role-arn: {}

podAnnotations: {}

podSecurityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetAverageUtilization: 80

nodeSelector: {}

tolerations: []

affinity: {}

variables: {}